[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 20_000
build_info = true
extra_output = ["storageLayout"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts"]

[rpc_endpoints]
sonic = "${MAINNET_RPC_URL}"

[etherscan]
sonic = { key = "${ETHERSCAN_API_KEY}", url = "https://api.sonicscan.org/api", chain = 146 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
