name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: false

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Foundry and system info
        run: |
          forge --version
          forge config
          solc --version

      - name: Run Forge fmt
        continue-on-error: true
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes --deny-warnings
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --deny-warnings
        env:
          FOUNDRY_FUZZ_RUNS: 256
          FOUNDRY_FUZZ_MAX_TEST_REJECTS: 65536
        id: test
